import type { Locale } from '@/lib/i18n'

type Row = [es: string, en: string, fr: string]

const COPY: Record<string, Row> = {
  'Проект': ['Proyecto', 'Project', 'Projet'],
  'Характеристики': ['Características', 'Characteristics', 'Caractéristiques'],
  'Строительные работы': ['Obra', 'Building work', 'Travaux'],
  'Сантехника и электрика': ['Fontanería y electricidad', 'Plumbing and electrics', 'Plomberie et électricité'],
  'Климат': ['Climatización', 'Climate', 'Climatisation'],
  'Отделка': ['Acabados', 'Finishes', 'Finitions'],
  'Столярные изделия': ['Carpintería', 'Carpentry', 'Menuiserie'],
  'Расчёт': ['Cálculo', 'Estimate', 'Estimation'],
  'Ремонт ванной': ['Reforma de baño', 'Bathroom renovation', 'Rénovation de salle de bains'],
  'Ремонт кухни': ['Reforma de cocina', 'Kitchen renovation', 'Rénovation de cuisine'],
  'Комплексный ремонт': ['Reforma integral', 'Full renovation', 'Rénovation complète'],
  'Проект и подготовка': ['Proyecto y preparación', 'Design and preparation', 'Projet et préparation'],
  'Климат и вентиляция': ['Climatización y ventilación', 'Climate and ventilation', 'Climatisation et ventilation'],
  'Отделочные материалы': ['Materiales y acabados', 'Finish materials', 'Matériaux de finition'],
  'Калькулятор ремонта': ['Calculadora de reforma', 'Renovation calculator', 'Calculateur de rénovation'],
  'Предварительная смета': ['Presupuesto preliminar', 'Preliminary estimate', 'Estimation préliminaire'],
  'без лишних вопросов.': ['sin preguntas innecesarias.', 'without irrelevant questions.', 'sans questions inutiles.'],
  'Вопросы меняются под выбранный тип ремонта. Расчёт адаптирован для проектов в Валенсии и показан в евро.': ['Las preguntas se adaptan al tipo de reforma. El cálculo está pensado para Valencia y se muestra en euros.', 'Questions adapt to the selected project. The estimate is tailored to Valencia and shown in euros.', 'Les questions s’adaptent au type de projet. L’estimation est conçue pour Valence et affichée en euros.'],
  'Этапы расчёта': ['Etapas del cálculo', 'Estimate stages', 'Étapes de l’estimation'],
  'Шаг': ['Paso', 'Step', 'Étape'],
  'Назад': ['Atrás', 'Back', 'Retour'],
  'Продолжить': ['Continuar', 'Continue', 'Continuer'],
  'Рассчитать': ['Calcular', 'Calculate', 'Calculer'],
  'Результат является предварительной оценкой. Точная стоимость определяется после замера и согласования спецификации.': ['El resultado es orientativo. El precio final se confirma tras la medición y la definición de la especificación.', 'The result is preliminary. The final price is confirmed after measurement and specification approval.', 'Le résultat est indicatif. Le prix final est confirmé après relevé et validation des choix.'],
  'Что будем ремонтировать?': ['¿Qué vamos a reformar?', 'What are we renovating?', 'Que souhaitez-vous rénover ?'],
  'Выберите тип проекта — следующие вопросы автоматически адаптируются и не будут содержать лишних пунктов.': ['Elige el tipo de proyecto. Las siguientes preguntas se adaptarán y no mostrarán opciones irrelevantes.', 'Choose the project type. The following questions adapt automatically and omit irrelevant options.', 'Choisissez le type de projet. Les questions suivantes s’adaptent automatiquement sans options inutiles.'],
  'Ванная комната': ['Baño', 'Bathroom', 'Salle de bains'],
  'Кухня': ['Cocina', 'Kitchen', 'Cuisine'],
  'Сантехника, гидроизоляция, плитка и мебель': ['Fontanería, impermeabilización, revestimientos y mueble', 'Plumbing, waterproofing, tiling and furniture', 'Plomberie, étanchéité, carrelage et meuble'],
  'Инженерия, отделка, гарнитур и столешница': ['Instalaciones, acabados, mobiliario y encimera', 'Services, finishes, units and worktop', 'Réseaux, finitions, meubles et plan de travail'],
  'Полное обновление квартиры или дома': ['Renovación completa de piso o casa', 'Complete apartment or house renovation', 'Rénovation complète d’un appartement ou d’une maison'],
  'Параметры ванной': ['Datos del baño', 'Bathroom details', 'Détails de la salle de bains'],
  'Параметры кухни': ['Datos de la cocina', 'Kitchen details', 'Détails de la cuisine'],
  'Параметры объекта': ['Datos del inmueble', 'Property details', 'Détails du bien'],
  'Нужны только размеры и текущее состояние помещения.': ['Solo necesitamos las medidas y el estado actual.', 'We only need the dimensions and current condition.', 'Nous avons seulement besoin des dimensions et de l’état actuel.'],
  'Площадь и состав объекта определяют объём комплексного ремонта.': ['La superficie y la distribución determinan el alcance de la reforma integral.', 'Area and layout determine the scope of a full renovation.', 'La surface et la composition déterminent l’ampleur d’une rénovation complète.'],
  'Площадь ванной': ['Superficie del baño', 'Bathroom area', 'Surface de la salle de bains'],
  'Площадь кухни': ['Superficie de la cocina', 'Kitchen area', 'Surface de la cuisine'],
  'Общая площадь объекта': ['Superficie total', 'Total area', 'Surface totale'],
  'Спальни': ['Dormitorios', 'Bedrooms', 'Chambres'],
  'Санузлы': ['Baños', 'Bathrooms', 'Salles de bains'],
  'Количество отдельных спален': ['Número de dormitorios', 'Number of bedrooms', 'Nombre de chambres'],
  'Ванные комнаты и гостевые санузлы': ['Baños y aseos', 'Bathrooms and guest WCs', 'Salles de bains et WC'],
  'Текущее состояние': ['Estado actual', 'Current condition', 'État actuel'],
  'Ванная в эксплуатации': ['Baño en uso', 'Bathroom in use', 'Salle de bains en service'],
  'Кухня в эксплуатации': ['Cocina en uso', 'Kitchen in use', 'Cuisine en service'],
  'Объект с отделкой': ['Inmueble terminado', 'Finished property', 'Bien avec finitions'],
  'Есть старая отделка и оборудование': ['Hay acabados y equipos existentes', 'Existing finishes and equipment', 'Finitions et équipements existants'],
  'Новостройка': ['Obra nueva', 'New build', 'Construction neuve'],
  'Помещение без чистовой отделки': ['Espacio sin acabados finales', 'Space without final finishes', 'Espace sans finitions'],
  'Только демонтаж и изменения, которые относятся к кухонной зоне.': ['Solo demoliciones y cambios relacionados con la cocina.', 'Only demolition and changes related to the kitchen.', 'Uniquement la démolition et les modifications liées à la cuisine.'],
  'Определим масштаб демонтажа, перепланировки и обновления полов.': ['Definimos la demolición, redistribución y renovación de suelos.', 'We define demolition, layout changes and floor renewal.', 'Nous définissons la démolition, la redistribution et la rénovation des sols.'],
  'Определим объём демонтажа и изменения планировки ванной.': ['Definimos la demolición y los cambios de distribución del baño.', 'We define demolition and bathroom layout changes.', 'Nous définissons la démolition et les modifications de la salle de bains.'],
  'Демонтировать существующую отделку и оборудование?': ['¿Retirar acabados y equipamiento existentes?', 'Remove existing finishes and equipment?', 'Déposer les finitions et équipements existants ?'],
  'Демонтировать существующую отделку?': ['¿Retirar los acabados existentes?', 'Remove existing finishes?', 'Déposer les finitions existantes ?'],
  'Нужен полный демонтаж существующей отделки?': ['¿Se necesita una demolición completa?', 'Is full demolition required?', 'Une démolition complète est-elle nécessaire ?'],
  'Менять расположение кухонной зоны?': ['¿Cambiar la ubicación de la cocina?', 'Move the kitchen area?', 'Déplacer la zone cuisine ?'],
  'Менять расположение сантехники?': ['¿Cambiar la ubicación de los sanitarios?', 'Move sanitary fixtures?', 'Déplacer les sanitaires ?'],
  'Объединять кухню с гостиной?': ['¿Unir cocina y salón?', 'Open the kitchen to the living room?', 'Ouvrir la cuisine sur le salon ?'],
  'Планируется перепланировка?': ['¿Se prevé redistribuir?', 'Are layout changes planned?', 'Une redistribution est-elle prévue ?'],
  'Полностью заменить напольные покрытия?': ['¿Cambiar todos los pavimentos?', 'Replace all floor finishes?', 'Remplacer tous les revêtements de sol ?'],
  'Перегородки': ['Tabiques', 'Partitions', 'Cloisons'],
  'Сколько перегородок нужно перенести или демонтировать': ['Tabiques a mover o demoler', 'Partitions to move or remove', 'Cloisons à déplacer ou déposer'],
  'Основная мокрая зона': ['Zona húmeda principal', 'Main wet area', 'Zone humide principale'],
  'Душевая': ['Ducha', 'Shower', 'Douche'],
  'Ванна': ['Bañera', 'Bath', 'Baignoire'],
  'Оставить': ['Mantener', 'Keep', 'Conserver'],
  'Новый поддон или душ в уровень пола': ['Plato nuevo o ducha a ras de suelo', 'New tray or level-access shower', 'Nouveau receveur ou douche de plain-pied'],
  'Установка новой ванны': ['Instalación de bañera nueva', 'Install a new bath', 'Pose d’une nouvelle baignoire'],
  'Сохранить текущую мокрую зону': ['Mantener la zona húmeda actual', 'Keep the current wet area', 'Conserver la zone humide actuelle'],
  'Выполнить новую гидроизоляцию?': ['¿Realizar una impermeabilización nueva?', 'Install new waterproofing?', 'Réaliser une nouvelle étanchéité ?'],
  'Да': ['Sí', 'Yes', 'Oui'],
  'Нет': ['No', 'No', 'Non'],
  'рекомендуем': ['recomendado', 'recommended', 'recommandé'],
  'Подключения и электрика, необходимые именно для новой кухни.': ['Conexiones e instalación eléctrica necesarias para la nueva cocina.', 'Connections and electrics required for the new kitchen.', 'Raccordements et électricité nécessaires à la nouvelle cuisine.'],
  'Только инженерные работы, которые относятся к ванной комнате.': ['Solo instalaciones relacionadas con el baño.', 'Only services related to the bathroom.', 'Uniquement les réseaux liés à la salle de bains.'],
  'Инженерные системы всего объекта без вопросов по отдельным помещениям.': ['Instalaciones de todo el inmueble, sin preguntas por estancia.', 'Whole-property services without room-by-room questions.', 'Réseaux de l’ensemble du bien, sans questions pièce par pièce.'],
  'Перенести или заменить кухонные трубы?': ['¿Mover o renovar las tuberías de cocina?', 'Move or replace kitchen pipework?', 'Déplacer ou remplacer les canalisations de cuisine ?'],
  'Заменить водопровод и канализацию?': ['¿Renovar agua y desagües?', 'Replace water and drainage pipes?', 'Remplacer l’alimentation et l’évacuation ?'],
  'Обновить электрику ванной?': ['¿Renovar la electricidad del baño?', 'Renew bathroom electrics?', 'Rénover l’électricité de la salle de bains ?'],
  'Обновить электрику кухни?': ['¿Renovar la electricidad de la cocina?', 'Renew kitchen electrics?', 'Rénover l’électricité de la cuisine ?'],
  'Полностью заменить водопровод и канализацию?': ['¿Renovar toda la fontanería?', 'Replace all plumbing?', 'Remplacer toute la plomberie ?'],
  'Полностью заменить электрику?': ['¿Renovar toda la electricidad?', 'Replace all electrics?', 'Remplacer toute l’électricité ?'],
  'Сантехнические точки': ['Puntos de fontanería', 'Plumbing points', 'Points de plomberie'],
  'Электрические точки': ['Puntos eléctricos', 'Electrical points', 'Points électriques'],
  'Сантехнические подключения': ['Conexiones de fontanería', 'Plumbing connections', 'Raccordements plomberie'],
  'Точки света и розетки': ['Luces y enchufes', 'Lights and sockets', 'Éclairage et prises'],
  'Климат ванной': ['Clima del baño', 'Bathroom climate', 'Confort de la salle de bains'],
  'Климат кухни': ['Clima de la cocina', 'Kitchen climate', 'Confort de la cuisine'],
  'Климат объекта': ['Climatización del inmueble', 'Property climate', 'Climatisation du bien'],
  'Вентиляция и отопление только в кухонной зоне.': ['Ventilación y calefacción solo en la cocina.', 'Ventilation and heating for the kitchen only.', 'Ventilation et chauffage de la cuisine uniquement.'],
  'Отопление, комфорт пола и правильный воздухообмен.': ['Calefacción, suelo confortable y ventilación adecuada.', 'Heating, floor comfort and proper ventilation.', 'Chauffage, confort du sol et bonne ventilation.'],
  'Выберите систему охлаждения и объём обновления отопления.': ['Elige la climatización y el alcance de la renovación de calefacción.', 'Choose cooling and the extent of heating renewal.', 'Choisissez la climatisation et l’ampleur de la rénovation du chauffage.'],
  'Тёплый пол?': ['¿Suelo radiante?', 'Underfloor heating?', 'Plancher chauffant ?'],
  'Тёплый пол на кухне?': ['¿Suelo radiante en la cocina?', 'Underfloor heating in the kitchen?', 'Plancher chauffant dans la cuisine ?'],
  'Тёплый пол во всём объекте?': ['¿Suelo radiante en todo el inmueble?', 'Underfloor heating throughout?', 'Plancher chauffant dans tout le bien ?'],
  'Новая вытяжная вентиляция?': ['¿Nueva ventilación mecánica?', 'New extract ventilation?', 'Nouvelle ventilation mécanique ?'],
  'Установить новую вытяжку и вентиляционный канал?': ['¿Nueva campana y conducto de ventilación?', 'New extractor and ventilation duct?', 'Nouvelle hotte et conduit de ventilation ?'],
  'Заменить радиаторы?': ['¿Sustituir radiadores?', 'Replace radiators?', 'Remplacer les radiateurs ?'],
  'Перенести или заменить радиатор?': ['¿Mover o sustituir el radiador?', 'Move or replace the radiator?', 'Déplacer ou remplacer le radiateur ?'],
  'Кондиционирование': ['Climatización', 'Air conditioning', 'Climatisation'],
  'Без новой системы': ['Sin sistema nuevo', 'No new system', 'Sans nouveau système'],
  'Сплит-системы': ['Equipos split', 'Split systems', 'Systèmes split'],
  'Отдельные блоки в основных комнатах': ['Equipos independientes en estancias principales', 'Individual units in main rooms', 'Unités individuelles dans les pièces principales'],
  'Канальная система': ['Sistema por conductos', 'Ducted system', 'Système gainable'],
  'Скрытая разводка по всему объекту': ['Distribución oculta por todo el inmueble', 'Concealed distribution throughout', 'Distribution dissimulée dans tout le bien'],
  'Отделка кухни': ['Acabados de cocina', 'Kitchen finishes', 'Finitions de cuisine'],
  'Отделка объекта': ['Acabados del inmueble', 'Property finishes', 'Finitions du bien'],
  'Отделка и покраска': ['Acabados y pintura', 'Finishes and painting', 'Finitions et peinture'],
  'Покрытия, которые непосредственно входят в ремонт кухонной зоны.': ['Revestimientos incluidos directamente en la reforma de cocina.', 'Finishes directly included in the kitchen renovation.', 'Revêtements inclus directement dans la rénovation de la cuisine.'],
  'Уровень материалов и подготовка поверхностей для всех помещений.': ['Nivel de materiales y preparación de superficies de todo el inmueble.', 'Material level and surface preparation throughout.', 'Niveau des matériaux et préparation des surfaces de tout le bien.'],
  'Выберите решение для стен и состояние потолка.': ['Elige el acabado de paredes y el estado del techo.', 'Choose wall finishes and ceiling condition.', 'Choisissez les finitions murales et l’état du plafond.'],
  'Напольное покрытие': ['Pavimento', 'Floor finish', 'Revêtement de sol'],
  'Плитка': ['Cerámica', 'Tile', 'Carrelage'],
  'Дерево': ['Madera', 'Wood', 'Bois'],
  'Микроцемент': ['Microcemento', 'Microcement', 'Microciment'],
  'Керамогранит или керамика': ['Porcelánico o cerámica', 'Porcelain or ceramic', 'Grès cérame ou céramique'],
  'Паркет или инженерная доска': ['Parquet o madera multicapa', 'Parquet or engineered wood', 'Parquet ou bois contrecollé'],
  'Бесшовное покрытие': ['Acabado continuo', 'Seamless finish', 'Revêtement sans joints'],
  'Кухонный фартук': ['Frente de cocina', 'Kitchen splashback', 'Crédence de cuisine'],
  'Единая поверхность со столешницей': ['Mismo material que la encimera', 'Same surface as worktop', 'Même matériau que le plan de travail'],
  'Стекло': ['Vidrio', 'Glass', 'Verre'],
  'Закалённая панель без швов': ['Panel templado sin juntas', 'Seamless toughened panel', 'Panneau trempé sans joints'],
  'Отделка стен': ['Acabado de paredes', 'Wall finish', 'Finition murale'],
  'Плитка полностью': ['Alicatado completo', 'Full-height tiling', 'Carrelage toute hauteur'],
  'От пола до потолка': ['De suelo a techo', 'Floor to ceiling', 'Du sol au plafond'],
  'Плитка в мокрых зонах': ['Azulejo en zonas húmedas', 'Tile in wet areas', 'Carrelage dans les zones humides'],
  'Остальные стены под покраску': ['Resto de paredes pintadas', 'Other walls painted', 'Autres murs peints'],
  'Бесшовная премиальная отделка': ['Acabado continuo premium', 'Premium seamless finish', 'Finition premium sans joints'],
  'Выравнивать и окрашивать потолок?': ['¿Nivelar y pintar el techo?', 'Level and paint the ceiling?', 'Niveler et peindre le plafond ?'],
  'Выравнивать стены под покраску?': ['¿Alisar las paredes para pintar?', 'Smooth walls before painting?', 'Lisser les murs avant peinture ?'],
  'Уровень отделки': ['Nivel de acabado', 'Finish level', 'Niveau de finition'],
  'Практичный': ['Práctico', 'Practical', 'Pratique'],
  'Надёжные серийные материалы': ['Materiales de serie fiables', 'Reliable standard materials', 'Matériaux de série fiables'],
  'Премиальный': ['Premium', 'Premium', 'Premium'],
  'Натуральные фактуры и сложные узлы': ['Texturas naturales y detalles complejos', 'Natural textures and complex detailing', 'Textures naturelles et détails complexes'],
  'Индивидуальный': ['Personalizado', 'Bespoke', 'Sur mesure'],
  'Эксклюзивные решения под проект': ['Soluciones exclusivas para el proyecto', 'Exclusive project-specific solutions', 'Solutions exclusives pour le projet'],
  'Потолки': ['Techos', 'Ceilings', 'Plafonds'],
  'Под покраску': ['Pintado', 'Painted', 'Peint'],
  'Выравнивание и окрашивание': ['Nivelado y pintura', 'Levelling and painting', 'Nivellement et peinture'],
  'Гипсокартон': ['Pladur', 'Plasterboard', 'Plaques de plâtre'],
  'Ниши и встроенное освещение': ['Foseados e iluminación integrada', 'Recesses and integrated lighting', 'Retombées et éclairage intégré'],
  'Натяжной': ['Tensado', 'Stretch ceiling', 'Plafond tendu'],
  'Быстрый монтаж полотна': ['Instalación rápida', 'Fast membrane installation', 'Pose rapide de la toile'],
  'Мебель и столярные изделия': ['Mobiliario y carpintería', 'Furniture and carpentry', 'Mobilier et menuiserie'],
  'Только кухонный гарнитур, столешница и дверь.': ['Solo mobiliario de cocina, encimera y puerta.', 'Kitchen units, worktop and door only.', 'Meubles de cuisine, plan de travail et porte uniquement.'],
  'Двери, окна и встроенное хранение для всего объекта.': ['Puertas, ventanas y almacenaje a medida para todo el inmueble.', 'Doors, windows and built-in storage throughout.', 'Portes, fenêtres et rangements intégrés dans tout le bien.'],
  'Последние позиции, относящиеся непосредственно к ванной.': ['Últimas partidas específicas del baño.', 'Final items specific to the bathroom.', 'Derniers éléments propres à la salle de bains.'],
  'Кухонный гарнитур': ['Mobiliario de cocina', 'Kitchen units', 'Meubles de cuisine'],
  'Сохранить': ['Mantener', 'Keep', 'Conserver'],
  'Оставить существующую мебель': ['Mantener el mobiliario existente', 'Keep existing furniture', 'Conserver le mobilier existant'],
  'Модульный': ['Modular', 'Modular', 'Modulaire'],
  'Готовые секции стандартных размеров': ['Módulos de medidas estándar', 'Standard-size units', 'Modules de dimensions standard'],
  'На заказ': ['A medida', 'Custom made', 'Sur mesure'],
  'Индивидуальная конфигурация': ['Configuración personalizada', 'Custom configuration', 'Configuration personnalisée'],
  'Столешница': ['Encimera', 'Worktop', 'Plan de travail'],
  'Ламинат': ['Laminado', 'Laminate', 'Stratifié'],
  'Практичный базовый вариант': ['Opción básica y práctica', 'Practical basic option', 'Option de base pratique'],
  'Кварц': ['Cuarzo', 'Quartz', 'Quartz'],
  'Прочная композитная поверхность': ['Superficie compuesta resistente', 'Durable composite surface', 'Surface composite résistante'],
  'Натуральный камень': ['Piedra natural', 'Natural stone', 'Pierre naturelle'],
  'Премиальная фактура': ['Textura premium', 'Premium texture', 'Texture premium'],
  'Дверь кухни': ['Puerta de cocina', 'Kitchen door', 'Porte de cuisine'],
  'Дверь ванной': ['Puerta del baño', 'Bathroom door', 'Porte de salle de bains'],
  'Без замены двери': ['Sin sustituir la puerta', 'Keep the door', 'Sans remplacer la porte'],
  'Заменить': ['Sustituir', 'Replace', 'Remplacer'],
  'Новая дверь и монтаж': ['Puerta nueva e instalación', 'New door and installation', 'Nouvelle porte et pose'],
  'Заменить межкомнатные двери?': ['¿Sustituir puertas interiores?', 'Replace internal doors?', 'Remplacer les portes intérieures ?'],
  'Межкомнатные двери': ['Puertas interiores', 'Internal doors', 'Portes intérieures'],
  'Количество новых дверных блоков': ['Número de puertas nuevas', 'Number of new door sets', 'Nombre de nouvelles portes'],
  'Заменить окна?': ['¿Sustituir ventanas?', 'Replace windows?', 'Remplacer les fenêtres ?'],
  'Окна': ['Ventanas', 'Windows', 'Fenêtres'],
  'Количество оконных блоков': ['Número de ventanas', 'Number of windows', 'Nombre de fenêtres'],
  'Нужно встроенное хранение на заказ?': ['¿Almacenaje empotrado a medida?', 'Custom built-in storage?', 'Rangements intégrés sur mesure ?'],
  'Тумба под раковину': ['Mueble de lavabo', 'Vanity unit', 'Meuble vasque'],
  'Не нужна': ['No hace falta', 'Not required', 'Non nécessaire'],
  'Без мебели': ['Sin mueble', 'No furniture', 'Sans meuble'],
  'Готовая': ['Estándar', 'Standard', 'Standard'],
  'Серийная тумба': ['Mueble de serie', 'Standard vanity', 'Meuble de série'],
  'По индивидуальным размерам': ['Según medidas', 'Made to measure', 'Aux dimensions du projet'],
  'Нужна встроенная ниша для хранения?': ['¿Nicho empotrado para almacenaje?', 'Built-in storage niche?', 'Niche de rangement intégrée ?'],
  'Собираем предварительную смету': ['Preparando el presupuesto preliminar', 'Preparing your preliminary estimate', 'Préparation de votre estimation'],
  'Учитываем выбранные работы и материалы…': ['Calculamos los trabajos y materiales seleccionados…', 'Calculating selected work and materials…', 'Calcul des travaux et matériaux sélectionnés…'],
  'WhatsApp готов': ['WhatsApp preparado', 'WhatsApp ready', 'WhatsApp prêt'],
  'Проверьте подготовленное сообщение в WhatsApp и нажмите «Отправить», чтобы передать параметры проекта.': ['Revisa el mensaje en WhatsApp y pulsa enviar para compartir los datos del proyecto.', 'Review the message in WhatsApp and press send to share the project details.', 'Vérifiez le message dans WhatsApp puis envoyez-le pour partager les informations du projet.'],
  'Новый расчёт': ['Nuevo cálculo', 'New estimate', 'Nouvelle estimation'],
  'Ориентировочный диапазон': ['Rango orientativo', 'Estimated range', 'Fourchette estimative'],
  'Средний ориентир:': ['Estimación media:', 'Average estimate:', 'Estimation moyenne :'],
  'Налоги и окончательная спецификация уточняются после замера.': ['Los impuestos y la especificación final se confirman tras la medición.', 'Taxes and final specifications are confirmed after measurement.', 'Les taxes et les choix finaux sont confirmés après relevé.'],
  'Следующий шаг': ['Siguiente paso', 'Next step', 'Prochaine étape'],
  'Получить точную смету': ['Recibir un presupuesto exacto', 'Get an accurate quote', 'Recevoir un devis précis'],
  'Оставьте контакты — параметры расчёта уже подготовлены.': ['Deja tus datos: los parámetros del cálculo ya están preparados.', 'Leave your details — the estimate parameters are ready.', 'Laissez vos coordonnées — les paramètres sont déjà préparés.'],
  'Имя': ['Nombre', 'Name', 'Nom'],
  'Телефон': ['Teléfono', 'Phone', 'Téléphone'],
  'Как к вам обращаться': ['¿Cómo te llamas?', 'How should we address you?', 'Comment vous appelez-vous ?'],
  'Отправить расчёт': ['Continuar en WhatsApp', 'Continue in WhatsApp', 'Continuer sur WhatsApp'],
  'Начать заново': ['Empezar de nuevo', 'Start again', 'Recommencer'],
}

export function calcText(value: string, locale: Locale) {
  if (locale === 'ru') return value
  const translated = COPY[value]
  if (!translated) return value
  return translated[locale === 'es' ? 0 : locale === 'en' ? 1 : 2]
}
